# Cleaning

Prior to performing EDA I conducted my cleaning process in this notebook. This notebook is the final result of the various cleaning methods performed, put into several functions. During the EDA process I actually updated this notebook with additional cleaning. 

## Import and Set Up Data

In [1]:
import pandas as pd
import numpy as np

# pd.set_option('max_columns', None)
# pd.set_option('max_rows', None)

In [2]:
#Loading the datasets to be used for the project
train_df = pd.read_csv('./datasets/train.csv')
test_df = pd.read_csv('./datasets/test.csv')

In [19]:
train_df.head(1)

PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley  \
Id                                                                           
109  533352170           60        RL           0.0     13517   Pave    NA   

    Lot Shape Land Contour Utilities  ... Screen Porch Pool Area Pool QC  \
Id                                    ...                                  
109       IR1          Lvl    AllPub  ...            0         0       0   

    Fence Misc Feature Misc Val Mo Sold  Yr Sold  Sale Type  SalePrice  
Id                                                                      
109     0           NA        0       3     2010        WD      130500  

[1 rows x 80 columns]

In [4]:
# seting the Id column to be the index for each of the dataframes
train_df.set_index('Id', inplace = True)
test_df.set_index('Id', inplace = True)

In [20]:
train_df.head(1)

PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley  \
Id                                                                           
109  533352170           60        RL           0.0     13517   Pave    NA   

    Lot Shape Land Contour Utilities  ... Screen Porch Pool Area Pool QC  \
Id                                    ...                                  
109       IR1          Lvl    AllPub  ...            0         0       0   

    Fence Misc Feature Misc Val Mo Sold  Yr Sold  Sale Type  SalePrice  
Id                                                                      
109     0           NA        0       3     2010        WD      130500  

[1 rows x 80 columns]

In [21]:
test_df.head(1)

PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley  \
Id                                                                            
2658  902301120          190        RM          69.0      9142   Pave  Grvl   

     Lot Shape Land Contour Utilities  ... 3Ssn Porch Screen Porch Pool Area  \
Id                                     ...                                     
2658       Reg          Lvl    AllPub  ...          0            0         0   

     Pool QC Fence Misc Feature Misc Val  Mo Sold  Yr Sold  Sale Type  
Id                                                                     
2658       0     0           NA        0        4     2006        WD   

[1 rows x 79 columns]

In [7]:
# Check for null/missing values
train_df.isnull().sum()

PID               0
MS SubClass       0
MS Zoning         0
Lot Frontage    330
Lot Area          0
               ... 
Misc Val          0
Mo Sold           0
Yr Sold           0
Sale Type         0
SalePrice         0
Length: 80, dtype: int64

In [8]:
# check types of each column
train_df.dtypes

PID               int64
MS SubClass       int64
MS Zoning        object
Lot Frontage    float64
Lot Area          int64
                 ...   
Misc Val          int64
Mo Sold           int64
Yr Sold           int64
Sale Type        object
SalePrice         int64
Length: 80, dtype: object

### Created a function that would output a readable version of all of the unique values and value counts for each column.

In [9]:
def columns_values(dataframe):
    for n in dataframe.columns:                               # cycle through the columns in dataframe
        column = n  
        value_counts = (dataframe[column].value_counts())     # run value counts for each column
        unique_values = (dataframe[column].unique())          # run unique values for each column 
        len_counts = len(value_counts)                        # how many items are counted in value counts
        len_unique = len(unique_values)                       # how many items are counted in unique values
        if (len(value_counts)< 100):                          # ignore columns where counts over 100
                print(f"{column} has length of {len_unique}") # print how many unique values there are
                print(unique_values)                          # print unique values for column 
                print("="*30)                                  
                print(f"{column} has length of {len_counts}") # print how many values are counted
                print(value_counts)                           # print unique values counted
                print("="*60)

In [10]:
columns_values(train_df)

MS SubClass has length of 16
[ 60  20  50 180 160  70 120 190  85  30  90  80  75  45  40 150]
MS SubClass has length of 16
20     770
60     394
50     198
120    132
30     101
70      90
160     88
80      86
90      75
190     46
85      28
75      16
45      11
180     11
40       4
150      1
Name: MS SubClass, dtype: int64
MS Zoning has length of 7
['RL' 'RM' 'FV' 'C (all)' 'A (agr)' 'RH' 'I (all)']
MS Zoning has length of 7
RL         1598
RM          316
FV          101
C (all)      19
RH           14
A (agr)       2
I (all)       1
Name: MS Zoning, dtype: int64
Street has length of 2
['Pave' 'Grvl']
Street has length of 2
Pave    2044
Grvl       7
Name: Street, dtype: int64
Alley has length of 3
[nan 'Pave' 'Grvl']
Alley has length of 2
Grvl    85
Pave    55
Name: Alley, dtype: int64
Lot Shape has length of 4
['IR1' 'Reg' 'IR2' 'IR3']
Lot Shape has length of 4
Reg    1295
IR1     692
IR2      55
IR3       9
Name: Lot Shape, dtype: int64
Land Contour has length of 4
['Lvl' 'HL

Bsmt Half Bath has length of 4
[ 0.  1. nan  2.]
Bsmt Half Bath has length of 3
0.0    1923
1.0     122
2.0       4
Name: Bsmt Half Bath, dtype: int64
Full Bath has length of 5
[2 1 3 0 4]
Full Bath has length of 5
2    1096
1     900
3      45
0       8
4       2
Name: Full Bath, dtype: int64
Half Bath has length of 3
[1 0 2]
Half Bath has length of 3
0    1308
1     725
2      18
Name: Half Bath, dtype: int64
Bedroom AbvGr has length of 8
[3 4 2 5 1 0 6 8]
Bedroom AbvGr has length of 8
3    1108
2     544
4     265
1      75
5      41
6      12
0       5
8       1
Name: Bedroom AbvGr, dtype: int64
Kitchen AbvGr has length of 4
[1 2 0 3]
Kitchen AbvGr has length of 4
1    1960
2      88
0       2
3       1
Name: Kitchen AbvGr, dtype: int64
Kitchen Qual has length of 4
['Gd' 'TA' 'Fa' 'Ex']
Kitchen Qual has length of 4
TA    1047
Gd     806
Ex     151
Fa      47
Name: Kitchen Qual, dtype: int64
TotRms AbvGrd has length of 14
[ 6  8  5  7  9  4 12 11 10  3 14  2 13 15]
TotRms AbvGrd has

### Here I created two functions to completed data cleaning for the training and test sets, this was updated throughout the EDA process.

In [11]:
# Credit to Haley Taft for showing me how this could work.
def clean_train(dataframe, inplace=True):
    ## BELOW HERE IS WHERE I SET MY MAPPING DICTIONARIES TO REPLACE VALUES IN THE DATAFRAME ##
    replace_values = {'Reg': 4, 'IR1': 3, 'IR2': 2, 'IR3': 1, 
     'AllPub': 4, 'NoSewr': 3, 'NoSeWa': 2, 'ELO': 1,
     'Gtl': 3, 'Mod': 2, 'Sev': 1,
     'Ex': 5, 'Gd': 4, 'TA': 3, 'Fa': 2, 'Po': 1,
     'Gd': 4, 'Av': 3, 'Mn': 2, 'No':1,
     'GLQ': 6, 'ALQ': 5, 'BLQ': 4, 'Rec': 3, 'LwQ': 2, 'Unf': 1,
     'N': 0, 'Y': 1,
     'SBrkr': 5, 'FuseA': 4, 'FuseF': 3, 'FuseP': 2, 'Mix': 1,
     'Typ': 8, 'Min1': 7, 'Min2': 6, 'Mod': 5, 'Maj1': 4, 'Maj2': 3, 'Sev': 2, 'Sal': 1,
     'Fin': 3, 'RFn': 2, 'Unf': 1,
     'Y': 3, 'P': 2, 'N': 1,
     'GdPrv': 4, 'MnPrv': 3, 'GdWo': 2, 'MnWw': 1, 'NA' : 0
     }
    replace_values_na = {np.nan: "NA"}
    replace_values_nan = {np.nan: 0}
    
    ## HERE IS WHERE I USED THE MAPPING DICTIONARIES TO REPLACE THE VALUES
    dataframe['Bsmt Qual'] = dataframe['Bsmt Qual'].replace(replace_values_nan)
    dataframe['Bsmt Cond'] = dataframe['Bsmt Cond'].replace(replace_values_nan)
    dataframe['Bsmt Exposure'] = dataframe['Bsmt Exposure'].replace(replace_values_nan)
    dataframe['BsmtFin Type 1'] = dataframe['BsmtFin Type 1'].replace(replace_values_nan)
    dataframe['BsmtFin Type 2'] = dataframe['BsmtFin Type 2'].replace(replace_values_nan)
    dataframe['Bsmt Full Bath'] = dataframe['Bsmt Full Bath'].replace(replace_values_nan)
    dataframe['Bsmt Half Bath'] = dataframe['Bsmt Half Bath'].replace(replace_values_nan)
    dataframe['Fireplace Qu'] = dataframe['Fireplace Qu'].replace(replace_values_nan)
    dataframe['Garage Finish'] = dataframe['Garage Finish'].replace(replace_values_nan)
    dataframe['Garage Qual'] = dataframe['Garage Qual'].replace(replace_values_nan)
    dataframe['Garage Cond'] = dataframe['Garage Cond'].replace(replace_values_nan)
    dataframe['Fireplace Qu'] = dataframe['Fireplace Qu'].replace(replace_values_nan)
    dataframe['Garage Cars'] = dataframe['Garage Cars'].replace(replace_values_nan)
    dataframe['Garage Area'] = dataframe['Garage Area'].replace(replace_values_nan)
    dataframe['Pool QC'] = dataframe['Pool QC'].replace(replace_values_nan)
    dataframe['Fence'] = dataframe['Fence'].replace(replace_values_nan)
    dataframe['Lot Frontage'] = dataframe['Lot Frontage'].replace(replace_values_nan)
    dataframe['Alley'] = dataframe['Alley'].replace(replace_values_na)
    dataframe['Mas Vnr Type'] = dataframe['Mas Vnr Type'].replace(replace_values_na)
    dataframe['Mas Vnr Area'] = dataframe['Mas Vnr Area'].replace(replace_values_nan)
    dataframe['Mas Vnr Area'] = dataframe['Mas Vnr Area'].replace(replace_values_nan)
    dataframe['BsmtFin SF 1'] = dataframe['BsmtFin SF 1'].replace(replace_values_nan)
    dataframe['BsmtFin SF 2'] = dataframe['BsmtFin SF 2'].replace(replace_values_nan)
    dataframe['Bsmt Unf SF'] = dataframe['Bsmt Unf SF'].replace(replace_values_nan)
    dataframe['Total Bsmt SF'] = dataframe['Total Bsmt SF'].replace(replace_values_nan)
    dataframe['Garage Type'] = dataframe['Garage Type'].replace(replace_values_na)
    dataframe['Garage Yr Blt'] = dataframe['Garage Yr Blt'].replace({np.nan: 1980})
    dataframe['Misc Feature'] = dataframe['Misc Feature'].replace(replace_values_na)
    dataframe['Electrical'] = dataframe['Electrical'].replace(replace_values_nan)
    dataframe = dataframe.replace(replace_values)
    
    ## AFTER EDA I DETERMINED THAT I WANTED TO REMOVE THE OUTLIERS BELOW BASED ON SQUARE FOOTAGE
    
    dataframe = dataframe[(dataframe['Gr Liv Area'] < 4000)]
    dataframe = dataframe[(dataframe['Lot Area'] < 40000)]
    
    ## AFTER EDA I DECIDED TO CREATE THIS FEATURE COLUMN
    dataframe['Exter Qual and Gr Liv Area'] = dataframe['Exter Qual'] * dataframe['Gr Liv Area']
   
    return dataframe


In [12]:
def clean_test(dataframe, inplace=True):
    ## BELOW HERE IS WHERE I SET MY MAPPING DICTIONARIES TO REPLACE VALUES IN THE DATAFRAME ##
    replace_values = {'Reg': 4, 'IR1': 3, 'IR2': 2, 'IR3': 1, 
     'AllPub': 4, 'NoSewr': 3, 'NoSeWa': 2, 'ELO': 1,
     'Gtl': 3, 'Mod': 2, 'Sev': 1,
     'Ex': 5, 'Gd': 4, 'TA': 3, 'Fa': 2, 'Po': 1,
     'Gd': 4, 'Av': 3, 'Mn': 2, 'No':1,
     'GLQ': 6, 'ALQ': 5, 'BLQ': 4, 'Rec': 3, 'LwQ': 2, 'Unf': 1,
     'N': 0, 'Y': 1,
     'SBrkr': 5, 'FuseA': 4, 'FuseF': 3, 'FuseP': 2, 'Mix': 1,
     'Typ': 8, 'Min1': 7, 'Min2': 6, 'Mod': 5, 'Maj1': 4, 'Maj2': 3, 'Sev': 2, 'Sal': 1,
     'Fin': 3, 'RFn': 2, 'Unf': 1,
     'Y': 3, 'P': 2, 'N': 1,
     'GdPrv': 4, 'MnPrv': 3, 'GdWo': 2, 'MnWw': 1, 'NA' : 0
     }
    replace_values_na = {np.nan: "NA"}
    replace_values_nan = {np.nan: 0}
    ## HERE IS WHERE I USED THE MAPPING DICTIONARIES TO REPLACE THE VALUES
    dataframe['Bsmt Qual'] = dataframe['Bsmt Qual'].replace(replace_values_nan)
    dataframe['Bsmt Cond'] = dataframe['Bsmt Cond'].replace(replace_values_nan)
    dataframe['Bsmt Exposure'] = dataframe['Bsmt Exposure'].replace(replace_values_nan)
    dataframe['BsmtFin Type 1'] = dataframe['BsmtFin Type 1'].replace(replace_values_nan)
    dataframe['BsmtFin Type 2'] = dataframe['BsmtFin Type 2'].replace(replace_values_nan)
    dataframe['Bsmt Full Bath'] = dataframe['Bsmt Full Bath'].replace(replace_values_nan)
    dataframe['Bsmt Half Bath'] = dataframe['Bsmt Half Bath'].replace(replace_values_nan)
    dataframe['Fireplace Qu'] = dataframe['Fireplace Qu'].replace(replace_values_nan)
    dataframe['Garage Finish'] = dataframe['Garage Finish'].replace(replace_values_nan)
    dataframe['Garage Qual'] = dataframe['Garage Qual'].replace(replace_values_nan)
    dataframe['Garage Cond'] = dataframe['Garage Cond'].replace(replace_values_nan)
    dataframe['Fireplace Qu'] = dataframe['Fireplace Qu'].replace(replace_values_nan)
    dataframe['Garage Cars'] = dataframe['Garage Cars'].replace(replace_values_nan)
    dataframe['Garage Area'] = dataframe['Garage Area'].replace(replace_values_nan)
    dataframe['Pool QC'] = dataframe['Pool QC'].replace(replace_values_nan)
    dataframe['Fence'] = dataframe['Fence'].replace(replace_values_nan)
    dataframe['Lot Frontage'] = dataframe['Lot Frontage'].replace(replace_values_nan)
    dataframe['Alley'] = dataframe['Alley'].replace(replace_values_na)
    dataframe['Mas Vnr Type'] = dataframe['Mas Vnr Type'].replace(replace_values_na)
    dataframe['Mas Vnr Area'] = dataframe['Mas Vnr Area'].replace(replace_values_nan)
    dataframe['Mas Vnr Area'] = dataframe['Mas Vnr Area'].replace(replace_values_nan)
    dataframe['BsmtFin SF 1'] = dataframe['BsmtFin SF 1'].replace(replace_values_nan)
    dataframe['BsmtFin SF 2'] = dataframe['BsmtFin SF 2'].replace(replace_values_nan)
    dataframe['Bsmt Unf SF'] = dataframe['Bsmt Unf SF'].replace(replace_values_nan)
    dataframe['Total Bsmt SF'] = dataframe['Total Bsmt SF'].replace(replace_values_nan)
    dataframe['Garage Type'] = dataframe['Garage Type'].replace(replace_values_na)
    dataframe['Garage Yr Blt'] = dataframe['Garage Yr Blt'].replace({np.nan: 1980})
    dataframe['Misc Feature'] = dataframe['Misc Feature'].replace(replace_values_na)
    dataframe['Electrical'] = dataframe['Electrical'].replace(replace_values_nan)
    dataframe = dataframe.replace(replace_values)
    
    ## create feature column with Exter Qual and Grand Living Area ##
    dataframe['Exter Qual and Gr Liv Area'] = dataframe['Exter Qual'] * dataframe['Gr Liv Area']
   
    return dataframe


In [13]:
# Using functions above to complete the cleaning on both sets
train_df2 = clean_train(train_df)
test_df2 = clean_test(test_df)


In [14]:
train_df2.shape

(2034, 81)

In [15]:
test_df2.shape

(878, 80)

In [16]:
train_df2.describe()

PID  MS SubClass  Lot Frontage      Lot Area    Lot Shape  \
count  2.034000e+03  2034.000000   2034.000000   2034.000000  2034.000000   
mean   7.130739e+08    57.141101     57.819076   9636.329400     3.603736   
std    1.886583e+08    42.814477     32.247120   4039.056246     0.558709   
min    5.263011e+08    20.000000      0.000000   1300.000000     1.000000   
25%    5.284582e+08    20.000000     44.000000   7500.000000     3.000000   
50%    5.354531e+08    50.000000     63.000000   9373.000000     4.000000   
75%    9.071758e+08    70.000000     78.000000  11433.250000     4.000000   
max    9.241520e+08   190.000000    313.000000  39384.000000     4.000000   

         Utilities   Land Slope  Overall Qual  Overall Cond   Year Built  ...  \
count  2034.000000  2034.000000   2034.000000   2034.000000  2034.000000  ...   
mean      3.998525     3.078171      6.107178      5.563422  1971.675516  ...   
std       0.049571     0.400793      1.419531      1.106774    30.238483  ...   
min       2.000000     2.000000      1.000000      1.000000  1872.000000  ...   
25%       4.000000     3.000000      5.000000      5.000000  1953.000000  ...   
50%       4.000000     3.000000      6.000000      5.000000  1974.000000  ...   
75%       4.000000     3.000000      7.000000      6.000000  2001.000000  ...   
max       4.000000     5.000000     10.000000      9.000000  2010.000000  ...   

        3Ssn Porch  Screen Porch    Pool Area      Pool QC        Fence  \
count  2034.000000   2034.000000  2034.000000  2034.000000  2034.000000   
mean      2.613078     16.320059     1.906096     0.011799     0.579646   
std      25.333763     56.972205    34.256225     0.210072     1.215087   
min       0.000000      0.000000     0.000000     0.000000     0.000000   
25%       0.000000      0.000000     0.000000     0.000000     0.000000   
50%       0.000000      0.000000     0.000000     0.000000     0.000000   
75%       0.000000      0.000000     0.000000     0.000000     0.000000   
max     508.000000    490.000000   800.000000     5.000000     4.000000   

           Misc Val      Mo Sold      Yr Sold      SalePrice  \
count   2034.000000  2034.000000  2034.000000    2034.000000   
mean      43.401672     6.215831  2007.777778  180661.483284   
std      435.948787     2.743346     1.312761   78182.888787   
min        0.000000     1.000000  2006.000000   12789.000000   
25%        0.000000     4.000000  2007.000000  129500.000000   
50%        0.000000     6.000000  2008.000000  162000.000000   
75%        0.000000     8.000000  2009.000000  213187.500000   
max    12500.000000    12.000000  2010.000000  611657.000000   

       Exter Qual and Gr Liv Area  
count                 2034.000000  
mean                  5196.705015  
std                   2265.272436  
min                    668.000000  
25%                   3414.000000  
50%                   4782.000000  
75%                   6412.500000  
max                  16950.000000  

[8 rows x 61 columns]

In [17]:
test_df2.describe()

PID  MS SubClass  Lot Frontage       Lot Area   Lot Shape  \
count  8.780000e+02   878.000000    878.000000     878.000000  878.000000   
mean   7.162867e+08    58.268793     56.872437   10307.033030    3.602506   
std    1.889103e+08    42.235407     34.269502   10002.674602    0.579264   
min    5.263021e+08    20.000000      0.000000    1477.000000    1.000000   
25%    5.284841e+08    20.000000     40.000000    7297.250000    3.000000   
50%    5.354542e+08    50.000000     60.000000    9446.000000    4.000000   
75%    9.071904e+08    70.000000     78.000000   11589.000000    4.000000   
max    1.007100e+09   190.000000    182.000000  215245.000000    4.000000   

        Utilities  Land Slope  Overall Qual  Overall Cond   Year Built  ...  \
count  878.000000  878.000000    878.000000    878.000000   878.000000  ...   
mean     3.998861    3.077449      6.050114      5.566059  1970.492027  ...   
std      0.033748    0.411817      1.369065      1.128903    30.395895  ...   
min      3.000000    2.000000      2.000000      1.000000  1880.000000  ...   
25%      4.000000    3.000000      5.000000      5.000000  1954.000000  ...   
50%      4.000000    3.000000      6.000000      5.000000  1972.000000  ...   
75%      4.000000    3.000000      7.000000      6.000000  1999.750000  ...   
max      4.000000    5.000000     10.000000      9.000000  2010.000000  ...   

       Enclosed Porch  3Ssn Porch  Screen Porch   Pool Area     Pool QC  \
count      878.000000  878.000000    878.000000  878.000000  878.000000   
mean        24.064920    2.597950     14.830296    1.884966    0.020501   
std         73.249463   24.962482     53.003794   29.916672    0.308805   
min          0.000000    0.000000      0.000000    0.000000    0.000000   
25%          0.000000    0.000000      0.000000    0.000000    0.000000   
50%          0.000000    0.000000      0.000000    0.000000    0.000000   
75%          0.000000    0.000000      0.000000    0.000000    0.000000   
max       1012.000000  360.000000    576.000000  555.000000    5.000000   

            Fence      Misc Val     Mo Sold      Yr Sold  \
count  878.000000    878.000000  878.000000   878.000000   
mean     0.586560     48.498861    6.202733  2007.825740   
std      1.224476    550.169317    2.642498     1.327861   
min      0.000000      0.000000    1.000000  2006.000000   
25%      0.000000      0.000000    5.000000  2007.000000   
50%      0.000000      0.000000    6.000000  2008.000000   
75%      0.000000      0.000000    8.000000  2009.000000   
max      4.000000  15500.000000   12.000000  2010.000000   

       Exter Qual and Gr Liv Area  
count                  878.000000  
mean                  5176.816629  
std                   2322.581662  
min                   1198.000000  
25%                   3393.750000  
50%                   4737.000000  
75%                   6345.250000  
max                  21580.000000  

[8 rows x 60 columns]

In [18]:
# creating new csv with cleaned dataframes
train_df2.to_csv('clean_train.csv')
test_df2.to_csv('clean_test.csv')